[env]
TERM = "alacritty"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[scrolling]
history = 50000

[window]
decorations = "none"
dynamic_title = false
opacity = 0.8
startup_mode = "Maximized"
title = "tramline"

[colors]
primary = { background = "#1e1e2e" }
